### ISSUE TITLE
Close tabs bar after unfocus with TZFocus

### ISSUE THREAD

**Issue by timsofteng** [Pocco81/TrueZen.nvim#27]
Hello. When I use `TZFocus` with experimental mode and then toggle it again tabs bar still exist with one single tab. Could it disappear after unfocus?
![image](https://user-images.githubusercontent.com/51912173/120632142-5321ba80-c471-11eb-89e4-bd6b70119774.png)

Updated
I noticed similar strange issue with `TZAtaraxis`. When I toggle it to back to my normal mode I get `set numbers` but I didn't use it before and tabs bar as well.

https://user-images.githubusercontent.com/51912173/120660426-fc77a900-c48f-11eb-9d0d-34ed42edbcab.mp4

**Comment by Pocco81** [comment]
Hey!

> Could it disappear after unfocus?

Since [this commit](bd12cbb5b832f3f340a21c593edf19b443db733f) you can by doing:
```lua
-- inside your truezen config
	events = {
		after_focus_mode_unfocuses = true
	},
```

And then:
```lua
local true_zen = require("true-zen")
true_zen.after_focus_mode_unfocuses = function()
    vim.cmd("set showtabline=0")
end
```

> I noticed similar strange issue with TZAtaraxis. When I toggle it to back to my normal mode I get set numbers but I didn't use it before and tabs bar as well.

That be configured in the settings. There is a table call `left` which interacts with the **numbers, relative numbers, signcolumns**, etc and then there is the `top` table that interacts with the **tabline** (what you called tabs bar). The settings in those tables have self-explanatory names. Let me know if you need help with that too!

**Comment by timsofteng** [comment]
@Pocco81 Thanks for response. 
Yep, I definitely need help.
Could truezen just back to my previous state which I have before it action?
E.g for `focus` feature. I really don't understand why should I write that event listener. If you open regular nvim tab with `:tabnew` and close buffer with :bd tabline will disappear by itself if you have only one tab.

Same for `araraxis`. If I haven't enabled numbers before why does it appears? Why plugin enable it by itself?

**Comment by Pocco81** [comment]
> Could truezen just back to my previous state which I have before it action?
```lua
        minimalist = {
            store_and_restore_settings = true, -- this is the "master setting", so to speak
            show_vals_to_read = {
                "shown_showtabline" -- or put whatever value that you want to be read from the config and not from the current state
            }
        },
```

> E.g for focus feature. I really don't understand why should I write that event listener

Because you asked me how to disappear the tabline. 

> If you open regular nvim tab with :tabnew and close buffer with :bd tabline will disappear by itself if you have only one tab.

When you run any of TrueZen's commands it will load it self and the settings, so in the case of the tabline, if you were to have it enabled in the `top = {}` config, it will be enabled while you are out of either Minimalist or Ataraxis mode.

> E.g for focus feature. I really don't understand why should I write that event listener. If you open regular nvim tab with :tabnew and close buffer with :bd tabline will disappear by itself if you have only one tab.
Same for araraxis. If I haven't enabled numbers before why does it appears? Why plugin enable it by itsel

You can achieve all of what you want configuring the settings. I know there a lot of them but remember that there are settings that take over/control other settings like `store_and_restore_settings` in the `minimalist = {}` table or the `just_do_it_for_me` setting in the `ataraxis = {}` table. Use those if you want something that just works.

**Comment by timsofteng** [comment]
I guess you completely dont understand me.
You suggest to use config for pretty common thing.
I said I your plugin enable `set number` which was desables before I toggle it. Is it ok?
Your plugin show tabline with only one single tab after toggle. Is it ok?
Why should I play with that configurations for pretty common things? For example this plugin just work as expect.
It dont trigger unexpeted numbers or tabline.
https://github.com/folke/zen-mode.nvim

**Comment by timsofteng** [comment]
> I guess you completely dont understand me.
> You suggest to use config for pretty common things.
> I said your plugin enable `set number` which was desables before I toggle it. Is it ok?
> Your plugin show tabline with only one single tab after toggle. Is it ok?
> Why should I play with that configurations for pretty common things? For example this plugin just work as expect.
> It dont trigger unexpeted numbers or tabline.
> https://github.com/folke/zen-mode.nvim

I apreciate your job with that plugin but that strange issues are absolutely strange.

**Comment by Pocco81** [comment]
TrueZen was created at a time when then Z-index feature didn't exist. Zen-mode uses that feature, but it doesn't allow much configuration like with TrueZen. The latter is more universal, has more integrations and thus, more to configure.

Eventhough TrueZen has features for allowing an "out of the box" experience, zen-mode is better in that aspect because it has less.

TrueZen also also has some other features unrelated to end goal of providing distraction free coding, for instance, minimalist and focus modes.

Feel free to use whichever works best for you!
