### ISSUE TITLE
Doesn't respect user settings when toggling off

### ISSUE THREAD

**Issue by oblitum** [Pocco81/TrueZen.nvim#30]
Hi, thanks for great plugin, I just tried it and when I toggle any mode off by executing the command again, I get `number` option set, but which I don't have set by default, so I get unexpected line numbers when back from zen mode.

**Comment by Pocco81** [comment]
Well there's:
```
minimalist = {
  store_and_restore_settings = true,
}
```

However I just noticed that there are some things that aren't working quite as expected related with that setting, but for now you can use it and it should all work as expected.

**Comment by oblitum** [comment]
@Pocco81 do I have to set `store_and_restore_settings = true` for each one of the modes provided? Because all of them have this behavior.

**Comment by Pocco81** [comment]
No no, Focus mode does not interact with any GUI components, and Ataraxis mode is an extension of Minimalist mode, thus you just need to add that to Minimalist. I'm considering enabling that feature by default actually. Would **you** like to have it enabled by default (once I fix the small bugs I was talking about earlier)?

**Comment by oblitum** [comment]
Yeah sure. I think not having it by default [go against POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by oblitum** [comment]
> Focus mode does not interact with any GUI components

I just tried `:TZFocus` and it disabled the signcolumn, then when back from it, the signcolumn kept hidden.

**Comment by Pocco81** [comment]
At this point I think I should apologize for the amount of bugs that ended up in the main branch without me noticing, but also thank you for spotting them! So far I've solved 3 (including the one you just mentioned about TZFocus disabling the signcolumn).

Sorry for the first impression you might've gotten from the plugin. I'll merge all of this fixes with main as soon as I'm done with all of them.

**Comment by Pocco81** [comment]
[Done](https://github.com/Pocco81/TrueZen.nvim/commits/main). I changed that defaults in order to accomplish POLA + fixed all the small bugs. I recommend you reinstall the plugin and then copy and paste the new defaults so that it'll work as expected.

**Comment by oblitum** [comment]
Nice thx.

**Comment by oblitum** [comment]
I just noticed that `:TZAtaraxis` doesn't restore original window layout when toggled off. Is that expected? In Goyo, ZenMode, that doesn't happen, and original window layout is restored back.

**Comment by Pocco81** [comment]
Well there is:
```
        integrations = {
            integration_tzfocus_tzataraxis = true,
        }
```

It simply run Focus mode before Ataraxis mode so that it will focus it, and then after you quit Ataraxis it will unfocus it you'll return to your layout. It also has some logic into it and doesn't break when you swtich windows or buffers or whatever. The only problem is that for some reason Galaxyline ends up showing in Ataraxis mode (in case you are using that statusline) no matter what you do to try and hide it.

I actually just improved it and since [this commit](https://github.com/Pocco81/TrueZen.nvim/commit/6b83df476bb3acf97ef6c3c66462d9075a41bdde) it should all work as expeceted (of course if you have focus_method setting set to "experimental", as stated in the README)
