### ISSUE TITLE
Galaxyline not hidden when TrueZen is at startup

### ISSUE THREAD

**Issue by euglevi** [Pocco81/TrueZen.nvim#34]
First of all, thank you for the plugin!

I havean with galaxyline not disappearing. This is only when I use TZAtaraxis from the start with the autocmd VimEnter line. When I toggle it from within Neovim I do not have any issues.

This is my TrueZen configuration.

```
local true_zen = require("true-zen")

true_zen.setup({
	ui = {
		bottom = {
			laststatus = 0,
			ruler = false,
			showmode = false,
			showcmd = false,
			cmdheight = 1,
		},
		top = {
			showtabline = 0,
		},
		left = {
			number = false,
			relativenumber = false,
			signcolumn = "no",
		},
	},
	modes = {
		ataraxis = {
			left_padding = 32,
			right_padding = 32,
			top_padding = 0,
			bottom_padding = 0,
			ideal_writing_area_width = 90,
			just_do_it_for_me = false,
			keep_default_fold_fillchars = true,
			custome_bg = "",
			bg_configuration = true,
			affected_higroups = {NonText = {}, ColorColumn = {}, VertSplit = {}, StatusLine = {}, StatusLineNC = {}, SignColumn = {}, FoldColumn = {}}
		},
		focus = {
			margin_of_error = 5,
			focus_method = "experimental"
		},
	},
	integrations = {
		galaxyline = true,
	},
})

true_zen.before_mode_ataraxis_off = function ()
	vim.api.nvim_command('w')
end

vim.cmd("autocmd VimEnter * TZAtaraxis")

```

**Comment by Pocco81** [comment]
Hey! This is not an issue, it's expected behavior . TrueZen does hides galaxyline, but, if in order of execution you load galaxyline after loading TrueZen or bot at startup you'll end up having galaxyline there. So my solution would be to load both after entering nvim. Here is what I mean:


https://user-images.githubusercontent.com/58336662/124946228-7988c780-dfd4-11eb-9b8a-ff6b33c7a069.mp4



At the beginning I was loading both plugins at startup but notice that when truezen was loaded I added the `vim.cmd("TZAtaraxis")` to enter Ataraxis mode. That didn't work. But if both plugins are loaded after entering vim (the VimEnter event) then they will work as expected because in order of execution:

* Enters vim
TrueZen & Galaxyline load -> TrueZen toggles Ataraxis mode -> Ataraxis mode hides Galaxyline


Here I used Packer.nvim (my favorite plugin manager) to help me out with the events, but you can achieve the same behavior with pretty much any other plugin manager that supports lazy loading and uses native vim events.

**Comment by Pocco81** [comment]
After doing some tests it seems that loading Galaxyline with the VimEnter event breaks the line itself, so it seems to be an issue with lazy loading galaxyline. I opened [this issue]([url](https://github.com/glepnir/galaxyline.nvim/issues/195)) in their repo.

**Comment by euglevi** [comment]
Thank you for this. I also tried to do what you first suggested (I also use packer.nvim) but it did not work out.
