### ISSUE TITLE
TZAtaraxis broken layout

### ISSUE THREAD

**Issue by AnatoleLucet** [Pocco81/TrueZen.nvim#36]
Hi :wave:, I'm not sure why, but TZAtaraxis doesn't seem to work very well on my end.

![](https://user-images.githubusercontent.com/35486736/125765050-c4086fe7-9b2b-4b58-9c30-ec6ecf94c87a.png)

I'm not sure how to debug this. Though it doesn't seem to be caused by a plugin.

Version:
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-82h9vU/neovim-0.5.0+ubuntu2+git202107142015-19a2e59f7-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-82h9vU/neovim-0.5.0+ubuntu2+git202107142015-19a2e59f7-d569569c9/build/config -I/build/neovim-82h9vU/neovim-0.5.0+ubuntu2+git202107142015-19a2e59f7-d569569c9/src -I/build/neovim-82h9vU/neovim-0.5.0+ubuntu2+git202107142015-19a2e59f7-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-82h9vU/neovim-0.5.0+ubuntu2+git202107142015-19a2e59f7-d569569c9/build/src/nvim/auto -I/build/neovim-82h9vU/neovim-0.5.0+ubuntu2+git202107142015-19a2e59f7-d569569c9/build/include
Compiled by buildd@lgw01-amd64-021
```

**Comment by Pocco81** [comment]
Hey! well you are using a very very new and under development version of nvim, maybe we could start debugging the problem from there. Could you try grabbing latest stable 0.5 (an appimage would be perfect for this) and running it again? If that doesn't help, could you try setting `splitright` and `splitright` in your nvim config + grab as well the [default config](https://github.com/Pocco81/TrueZen.nvim#setup-configuration) for truezen in the README?

Also, may I see your current truezen config? yesterday I changed some settings so maybe you haven't updated it and it broke because of that. Who knows :shrug:

**Comment by marty-oehme** [comment]
I am just trying out TrueZen for the first time and have the exact same problem - on version
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
```

The issue is basically exactly the same as @AnatoleLucet , with the actual buffer appearing to the right-hand side of the window and the cursor being stuck in a 'non-modifiable' buffer on the left.

My settings are very basic, with everything being default except tmux, galaxyline, and gitsigns integrations activated (using packer):
```lua
    use {
        'Pocco81/TrueZen.nvim',
        config = function()
            require("true-zen").setup({
                integrations = {gitsigns = true, galaxyline = true, tmux = true}
            })
        end
    } -- provide distraction free writing
```
The three integrations appear to work fine as well (tmux statusline disappears and reappears, as does galaxyline and gitsigns) and the same problem persists if I use an all-default configuration.

As soon as I set both `splitright` and `splitbelow` it works perfectly fine, however. 
Are these settings mandatory for the plugin?

**Comment by Pocco81** [comment]
My bad. I just checked the code and the part that ensures this types of settings was evaluating for the wrong conditional. That probably slipped in during the refactor.

I'll fix that now.

**Comment by Pocco81** [comment]
now everything should work regardless of you having `splitbelow` and `splitright` set.

**Comment by marty-oehme** [comment]
Wow that was fast!
Just checked it quickly and it seems to work perfectly well again, even without having set those two settings.

Thank you so much for an amazing plugin, I like it a lot already and will test drive it a bit further in the coming days.

**Comment by Pocco81** [comment]
You don't need to have those settings *set*. Because TrueZen will only enable them while on Ataraxis Mode and then it restores them to whatever you had them before after exiting.

Thanks for liking my plugin :)
