### ISSUE TITLE
Incompatibility with Lualine

### ISSUE THREAD

**Issue by curiousyogurt** [Pocco81/TrueZen.nvim#38]
When using Lualine.nvim (https://github.com/hoob3rt/lualine.nvim), Ataraxis mode has remnant of some status bar at the top.  I've confirmed this is an interaction with Lualine: everything works fine if Lualine is not running.  Would it be possible to accommodate the use of Lualine?

<img width="942" alt="Screen Shot 2021-07-18 at 6 02 08 PM" src="https://user-images.githubusercontent.com/417960/126088531-d8b41e7f-4fe7-4024-b398-0acaa0b3c6b0.png">

**Comment by Pocco81** [comment]
I'm sorry but I don't use LuaLine. However, I think it's a "lualine problem" (just guessing), because @shaunsingh, a lualine user, opened #32 and in the screenshot he attached lualine didn't have the top bar. Could you first search for what that thing is on lualine and if possible how to disable it externally (e.g. with commands)?

**Comment by curiousyogurt** [comment]
So, you can disable lualine for certain filetypes, but that seems to make no difference as to how TZ interacts (the bar is still there).  With a little more exploring, it seems to me that TZ is creates several windows as a means to position the main text.  

First, when I start TZAtaraxis with a "t10" option, I get the same bar in the screenshot above, but 10 lines down.  But I can use <Ctrl-w>w repeatedly to get into that top window; and as soon as I do, the top bar turns into what is recognizably lualine.  So I agree with you that there's something going on with lualine.

Second, I can turn off lualine normally with `:set laststatus=0`; but that doesn't seem to work in TZ (even when directed at the window that TZ opens where the bar is).  I don't know if that helps at all.

**Comment by Pocco81** [comment]
I can't even hide the [lualine's tabline](https://github.com/hoob3rt/lualine.nvim#tabline) outside of truezen...

https://user-images.githubusercontent.com/58336662/126396374-9764a469-bdb0-4361-936b-73daeacb33e3.mp4

As you can see even my normal tabline (bufferline.nvim) gets hidden with `showtabline=0`. I'm sorry but if one can't even hide lualine's tabline normally then it won't be possible to hide it on TrueZen either. 

I think you can disable it in the configuration:

![image](https://user-images.githubusercontent.com/58336662/126396852-dc9abaf5-771a-497c-96b7-3f818c88f873.png)

But regardless of that, we need a way to control the tabline outside of the config, with commands or something. Maybe you should consider opening an issue in Lualine's repo, because right now I can't do much, that's why I'm closing the issue, for now...

**Comment by shaunsingh** [comment]
I have it disabled in my configuration, in case you were wondering. Lualine doesn't seem to play very nice with vim commands

**Comment by Pocco81** [comment]
Yeah... Even with horizontal splits that thing still appears... Btw have you tried galaxyline before? It integrates perfectly with truezen :)

![image](https://user-images.githubusercontent.com/58336662/126397584-c4c9f6ce-2e97-48e6-b876-15072dc43ebd.png)

And also looks very good:

![image](https://user-images.githubusercontent.com/58336662/126397610-8e9696f5-27e3-45e9-a6aa-e6f6d7f832d4.png)

**Comment by shaunsingh** [comment]
I'm looking to switch to galaxy line soon. It was a bit harder to configure (which is what swayed me to lualine) but looks like galaxy line is faster and looks better. Might be worth the time investment to switch

**Comment by Pocco81** [comment]
Here is my config: https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev-mnc/.config/nvim/lua/plugins/statusline.lua

just copy and paste it and it should work out of the box :+1:

**Comment by Pocco81** [comment]
Hey! kinda late but I ended finding a way to fix this: #57
