### ISSUE TITLE
Ideal Writing Width Error

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [Pocco81/TrueZen.nvim#40]
Whenever I attempt to use `TrueZen` with any configuration at all, even only changing one setting, I get these errors

```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua /home/user/.config/nvim/lua/hook.lua:43: Vim(lua):E5108: Error executing lua ...im/lua
/true-zen/services/modes/mode-ataraxis/service.lua:145: attempt to index field 'ideal_writing_area_width' (a nil
value)
```

My configuration is [here](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/master/src/configs/nvim/lua/plugin.lua#L151). I have tried removing all settings and it works, but even adding just one settings causes me this error.

**Comment by Pocco81** [comment]
Ideal writing area receives a table with integer(s) and/or strings. Checkout the [configuration](https://github.com/Pocco81/TrueZen.nvim#-configuration) section.

In your case you'd want that to be:

```lua
ideal_writing_area_width = {0}
```

Actually, this setting was changed very recently, so next time make sure you  check "notices" section out before posting an issue, because maybe x setting might be deprecated, like happened here.
