### ISSUE TITLE
Minimalist mode does not close after activating Ataraxis from inside of it.

### ISSUE THREAD

**Issue by luiz00martins** [Pocco81/TrueZen.nvim#41]
It seems like Minimalist mode gets stuck if you activate Ataraxis inside of it.

How to reproduce
----

1. Activate Minimalist mode with `:TZMinimalist`.
2. While in Minimalist mode, activate Ataraxis mode with `TZAtaraxis`.
3. Deactivate Ataraxis mode with `:TZAtaraxis`. This brings Minimalist mode back.
4. Try to deactivate Minimalist mode with `:TZMinimalist`

Expected behaviour vs Actual behaviour
----

I expected that, since I was in Minimalist mode in the last step, `:TZMinimalist` would deactivate it. However, it stays in Minimalist mode.

**Comment by Pocco81** [comment]
Hey! Why would you nest TZMnimalist and TZAtaraxis? I think it's very clear (in the README) that Ataraxis is a super extension of Minimalist mode that adds "padding" to the borders of the screen... or isn't clear? It simply means that Ataraxis uses Minimalist mode as an "engine".

So like when you first run `TZAtaraxis` if will turn on `Minimalist mode` (not toggle it because it doesn't make sense to do that), and when you turn on that it will save some variables like your current tabline hight, numbers, signcolumn, etc... and when you untoggle it it restores those values.

> Try to deactivate Minimalist mode with :TZMinimalist

That's the thing, it's already deactivated! what happens is that the vars it saved are the ones from where you were before: Minimalist mode.

![image](https://user-images.githubusercontent.com/58336662/126377873-797b4f5b-456a-4e15-82f3-04f724eb8dd8.png)

Let me know if I need to clarify this better in the README! :+1:

**Comment by luiz00martins** [comment]
It isn't my intention to use them nested. The problem is when a user accidentally activates one inside the other.

> That's the thing, it's already deactivated!

In my testing, the buffer still looks like Minimalist mode, even after deactivating Ataraxis, and I'm forced to restart neovim to bring it back to normal.

**Comment by Pocco81** [comment]
It looks like minimalist mode because Ataraxis ran Minimalist mode while you where inside of the Minimalist mode, and the latter saved the values of `showtabline`, `laststatus`, etc... from the Minimalist mode you where in, and restore them after quitting Ataraxis.

**Comment by luiz00martins** [comment]
I see. Still, I would consider it unexpected behaviour/a bug. It's certainly not my intention as a user to get "stuck" in that layout after trying to disable it in both ways. It seems like this is less intended behaviour, and more the result of an implementation detail.

**Comment by Pocco81** [comment]
Fair enough. I'll add something to avoid toggling it twice.

**Comment by Pocco81** [comment]
> I expected that, since I was in Minimalist mode in the last step, :TZMinimalist would deactivate it.

https://user-images.githubusercontent.com/58336662/126525446-ca1ae987-5438-4daf-8023-6a1a41784975.mp4

Now it does :)
