### ISSUE TITLE
Style: Tabs or spaces?

### ISSUE THREAD

**Issue by Groctel** [Pocco81/TrueZen.nvim#62]
Hi!

I'm looking at your code to try to fix #61 and have found instances where tabs are written instead of spaces. EG:
![image](https://user-images.githubusercontent.com/32376781/132333367-930159d8-83bc-407c-8b12-c33b1b3b1f6d.png)

I can send you a quick PR using the style you like and adding a comment at the end of the files to enforce that style so there's no more need for issues like #21. Tell me what your preferred style is and I'll update it in a moment :)

**Comment by Pocco81** [comment]
Oh I didn't know stylua hadn't formatted those things... I'd really appreciate a PR to fix it :) and if you ask me, I prefer tabs over spaces (see the stylua file).

About #61, the issue is in [this file](https://github.com/Pocco81/TrueZen.nvim/blob/main/lua/true-zen/services/modes/mode-ataraxis/modules/hi_group.lua#L116), to be more precise, on [this line](https://github.com/Pocco81/TrueZen.nvim/blob/main/lua/true-zen/services/modes/mode-ataraxis/modules/hi_group.lua#L116), I just haven't had time to fix it. Don't worry about that tho, now that I think about it the current handling looks kind of "ugly", so I'll probably replace it with something better.

**Comment by Pocco81** [comment]
I ended up reformatted the whole project with Stylua. Should be looking good now :+1:

**Comment by Groctel** [comment]
Thank you very much for fixing this and #61! I've had two very busy days and couldn't sit down to contribute a single line. I'll take a peek into the style tomorrow in case there's something missing :)

Also... tab gang!

**Comment by Pocco81** [comment]
Tab gang forever ;)

**Comment by Groctel** [comment]
I've found a couple of cases with inconsistencies and was going to PR you but I left my private keys at home lol. After completely fixing spaces into tabs I can do a few more things in a couple minutes:

I can change all of your `api.nvim.exec()` calls to one the following formats:

**Option 1:**

```lua
	api.nvim_exec([[
		aug feline
			au!
			au WinEnter,BufEnter * set statusline<
			au WinLeave,BufLeave * lua vim.wo.statusline=require'feline'.statusline()
			au ColorScheme * lua require'feline'.reset_highlights()
		aug END
	]], false)
```

**Option 2:**

```lua
		api.nvim_exec(
		[[
			augroup exit_ataraxis_too
				autocmd!
			augroup END
		]],
			false
		)
```

Or something between the two, I find it relaxing taking the time to reformat functions, so be greedy about it and any other blocks you want to see reestructured ;)

I can also append a vim format comment at the end of all your files so tabs are enforced by default. Tell me what you prefer and I'll do it when I get home :D

**Comment by Pocco81** [comment]
The current thing was caused by stylua, so we gotta put the "-- stylua ignore" things on those.

**Comment by Groctel** [comment]
What do you mean with *the current thing*?

**Comment by Pocco81** [comment]
What you called _option 2_, which is how it's currently formatted the code.

**Comment by Groctel** [comment]
So, sorry for asking too much, just to confirm: Do you prefer option 1 and prepend `-- stylua ignore` before them or prepend it with option 2?

**Comment by Pocco81** [comment]
Opt 1 with the `-- stylua ignore`.
