### ISSUE TITLE
Galaxyline shows grey lines above/below with integration enabled

### ISSUE THREAD

**Issue by shaunsingh** [Pocco81/TrueZen.nvim#64]
Switched recently from lualine to galaxyline, but I have have these bars now
![image](https://user-images.githubusercontent.com/71196912/133527833-786946a3-ddd8-426f-b378-47ed2d38bc0e.png)

Truezen config: 
https://github.com/shaunsingh/vimrc-dotfiles/blob/5a3558bb7f4a29f0faa6ae9f578b2d4b29c0e9e8/.config/nvim/init.lua#L1324

**Comment by Pocco81** [comment]
This happens because in your config you haven't enabled those hi groups in the config for the Ataraxis mode. I actually changed this recently, here is a before and after comparison:

![image](https://user-images.githubusercontent.com/58336662/133536565-3b1a8f8e-9aaf-4c74-8295-82cbd9e19100.png)

Remember you can always omit that part and TrueZen will pick the default values.

**Comment by shaunsingh** [comment]
Ah, sorry I missed that. Thank you for the great plugin and all the help!
