### ISSUE TITLE
which color scheme is being used in screenshot 😝

### ISSUE THREAD

**Issue by Aneeqasif** [Pocco81/TrueZen.nvim#79]
kindda very bad thing to ask such a question in github issues but heheh :D
please tell which color scheme you are using

**Comment by Pocco81** [comment]
Oh well I took that screenshot a long time ago so I don't remember the exact name of the plugin I was using. I do recall the color scheme being One Dark tho! Nowadays, however, I find myself using [**Catppuccin**](https://github.com/catppuccin/nvim) most of the time since it's less visually obtrusive and comes in several variants:


![image](https://user-images.githubusercontent.com/58336662/176817012-18ca0b34-e31f-44d7-a9f8-1fdae3a56d71.png)

> kindda very bad thing to ask such a question in github issues but heheh :D

don't worry about that ;)
